import { QueryInterface } from "sequelize";

export const up = async (queryInterface: QueryInterface) => {
  await queryInterface.bulkInsert('rooms', [
    {
      "id": 1,
      "name": "NewApt D1 - Cozy studio - NU apt - 500m Bui Vien!",
      "guestCount": 3,
      "bedRoomCount": 1,
      "bedCount": 1,
      "bathRoomCount": 1,
      "description": "Tự nhận phòng\r\nTự nhận phòng bằng khóa thông minh.\r\nDinh Long là Chủ nhà siêu cấp\r\nChủ nhà siêu cấp là những chủ nhà có kinh nghiệm, được đánh giá cao và là những người cam kết mang lại quãng thời gian ở tuyệt vời cho khách.",
      "price": 28,
      "hasWashingMachine": true,
      "hasIronBoard": true,
      "hasTV": true,
      "hasAirConditioner": false,
      "hasWifi": true,
      "hasKitchen": false,
      "hasParking": true,
      "hasSwimmingPool": true,
      "hasIron": true,
      "locationId": 1,
      "photo": "https://airbnbnew.cybersoft.edu.vn/images/phong1.jpg"
    },
    {
      "id": 2,
      "name": "STUDIO MỚI NETFLIX MIỄN PHÍ/ĐỖ XE MIỄN PHÍ",
      "guestCount": 2,
      "bedRoomCount": 1,
      "bedCount": 1,
      "bathRoomCount": 1,
      "description": "Không gian riêng để làm việc\r\nMột khu vực chung có Wi-fi, phù hợp để làm việc.\r\nTự nhận phòng\r\nTự nhận phòng bằng khóa thông minh.\r\nKim Nam là Chủ nhà siêu cấp\r\nChủ nhà siêu cấp là những chủ nhà có kinh nghiệm, được đánh giá cao và là những người cam kết mang lại quãng thời gian ở tuyệt vời cho khách.",
      "price": 21,
      "hasWashingMachine": true,
      "hasIronBoard": true,
      "hasTV": true,
      "hasAirConditioner": true,
      "hasWifi": true,
      "hasKitchen": true,
      "hasParking": false,
      "hasSwimmingPool": false,
      "hasIron": false,
      "locationId": 1,
      "photo": "https://airbnbnew.cybersoft.edu.vn/images/phong2.png"
    },
    {
      "id": 3,
      "name": "Phòng sang trọng với ban công tại D.1 - 200m đến Bitexco",
      "guestCount": 2,
      "bedRoomCount": 1,
      "bedCount": 1,
      "bathRoomCount": 1,
      "description": "Emmy là Chủ nhà siêu cấp\r\nChủ nhà siêu cấp là những chủ nhà có kinh nghiệm, được đánh giá cao và là những người cam kết mang lại quãng thời gian ở tuyệt vời cho khách.\r\nTrải nghiệm nhận phòng tuyệt vời\r\n100% khách gần đây đã xếp hạng 5 sao cho quy trình nhận phòng.\r\nHủy miễn phí trước 28 thg 9.",
      "price": 17,
      "hasWashingMachine": true,
      "hasIronBoard": true,
      "hasTV": true,
      "hasAirConditioner": false,
      "hasWifi": false,
      "hasKitchen": false,
      "hasParking": true,
      "hasSwimmingPool": true,
      "hasIron": true,
      "locationId": 1,
      "photo": "https://airbnbnew.cybersoft.edu.vn/images/phong3.png"
    },
    {
      "id": 4,
      "name": "Closer home!!!!",
      "guestCount": 4,
      "bedRoomCount": 2,
      "bedCount": 2,
      "bathRoomCount": 2,
      "description": "Hieu là Chủ nhà siêu cấp\r\nChủ nhà siêu cấp là những chủ nhà có kinh nghiệm, được đánh giá cao và là những người cam kết mang lại quãng thời gian ở tuyệt vời cho khách.\r\nĐịa điểm tuyệt vời\r\n100% khách gần đây đã xếp hạng 5 sao cho vị trí này.\r\nTrải nghiệm nhận phòng tuyệt vời\r\n100% khách gần đây đã xếp hạng 5 sao cho quy trình nhận phòng.",
      "price": 28,
      "hasWashingMachine": true,
      "hasIronBoard": true,
      "hasTV": true,
      "hasAirConditioner": true,
      "hasWifi": true,
      "hasKitchen": false,
      "hasParking": false,
      "hasSwimmingPool": false,
      "hasIron": false,
      "locationId": 2,
      "photo": "https://airbnbnew.cybersoft.edu.vn/images/phong4.png"
    },
    {
      "id": 5,
      "name": "Toàn bộ quê hương phải của Gi ngay trung tâm Cần Thơ",
      "guestCount": 4,
      "bedRoomCount": 2,
      "bedCount": 2,
      "bathRoomCount": 2,
      "description": "Giang là Chủ nhà siêu cấp\r\nChủ nhà siêu cấp là những chủ nhà có kinh nghiệm, được đánh giá cao và là những người cam kết mang lại quãng thời gian ở tuyệt vời cho khách.\r\nĐịa điểm tuyệt vời\r\n94% khách gần đây đã xếp hạng 5 sao cho vị trí này.\r\nTrải nghiệm nhận phòng tuyệt vời\r\n94% khách gần đây đã xếp hạng 5 sao cho quy trình nhận phòng.",
      "price": 25,
      "hasWashingMachine": true,
      "hasIronBoard": true,
      "hasTV": true,
      "hasAirConditioner": true,
      "hasWifi": false,
      "hasKitchen": false,
      "hasParking": true,
      "hasSwimmingPool": false,
      "hasIron": true,
      "locationId": 2,
      "photo": "https://airbnbnew.cybersoft.edu.vn/images/phong5.png"
    },
    {
      "id": 6,
      "name": "Ngôi nhà có hoa, nắng đẹp, trung tâm Cần Thơ",
      "guestCount": 4,
      "bedRoomCount": 1,
      "bedCount": 2,
      "bathRoomCount": 2,
      "description": "Tự nhận phòng\r\nTự nhận phòng với hộp khóa an toàn.\r\nDang là Chủ nhà siêu cấp\r\nChủ nhà siêu cấp là những chủ nhà có kinh nghiệm, được đánh giá cao và là những người cam kết mang lại quãng thời gian ở tuyệt vời cho khách.",
      "price": 21,
      "hasWashingMachine": true,
      "hasIronBoard": true,
      "hasTV": true,
      "hasAirConditioner": true,
      "hasWifi": true,
      "hasKitchen": true,
      "hasParking": false,
      "hasSwimmingPool": false,
      "hasIron": false,
      "locationId": 2,
      "photo": "https://airbnbnew.cybersoft.edu.vn/images/phong6.png"
    },
    {
      "id": 7,
      "name": "Near Hon Chong-Quiet Seaview Studio to beach",
      "guestCount": 2,
      "bedRoomCount": 1,
      "bedCount": 1,
      "bathRoomCount": 1,
      "description": "là nơi ẩn náu mới đưa khách tham quan một hành trình kỳ thú vào bãi biển Nha Trang. Chỉ 2 phút đi bộ ra bãi biển!\r\nCâu chuyện về Trăng tròn được diễn giải lại một cách nghệ thuật theo lối trang trí sang trọng, cổ điển của ngôi nhà – một phiên bản đương đại của thần thoại truyền thống được kể bằng đồ nội thất kết hợp các chi tiết phong cách với các yếu tố Việt cổ. Chúng tôi kết hợp dịch vụ lưu trú truyền thống của châu Á với các tiện ích hiểu biết về công nghệ,",
      "price": 10,
      "hasWashingMachine": true,
      "hasIronBoard": true,
      "hasTV": true,
      "hasAirConditioner": false,
      "hasWifi": false,
      "hasKitchen": false,
      "hasParking": true,
      "hasSwimmingPool": true,
      "hasIron": true,
      "locationId": 3,
      "photo": "https://airbnbnew.cybersoft.edu.vn/images/phong7.png"
    },
    {
      "id": 8,
      "name": "Tầng 25 Căn hộ 1 phòng ngủ ấm cúng và hiện đại",
      "guestCount": 4,
      "bedRoomCount": 1,
      "bedCount": 2,
      "bathRoomCount": 1,
      "description": "Phòng ngủ ấm cúng và Morden 1 ở tầng 25. Cảm giác như ở nhà khi qua đêm ở đây! Mọi chi tiết trong căn hộ đều đi kèm với tinh thần nghệ thuật.\r\n\r\nChỗ ở\r\nToàn bộ căn hộ sẽ là của bạn! Sử dụng miễn phí tiện nghi và đồ dùng nhà bếp của chúng tôi",
      "price": 15,
      "hasWashingMachine": false,
      "hasIronBoard": false,
      "hasTV": true,
      "hasAirConditioner": true,
      "hasWifi": true,
      "hasKitchen": true,
      "hasParking": true,
      "hasSwimmingPool": true,
      "hasIron": true,
      "locationId": 3,
      "photo": "https://airbnbnew.cybersoft.edu.vn/images/phong8.png"
    },
    {
      "id": 9,
      "name": "Căn hộ mặt tiền Economy Beach với chế độ ngắm bình minh",
      "guestCount": 4,
      "bedRoomCount": 1,
      "bedCount": 2,
      "bathRoomCount": 1,
      "description": "Căn hộ của tôi là căn hộ mặt tiền bãi biển, hướng ra bãi biển. Bạn có thể tận hưởng bình minh từ cửa sổ.\r\nCăn hộ có thể cho thuê tối đa 4 người với 2 giường đôi. Tọa lạc tại trung tâm thành phố với nhiều nhà hàng và siêu thị xung quanh.",
      "price": 18,
      "hasWashingMachine": true,
      "hasIronBoard": false,
      "hasTV": true,
      "hasAirConditioner": false,
      "hasWifi": true,
      "hasKitchen": true,
      "hasParking": false,
      "hasSwimmingPool": false,
      "hasIron": true,
      "locationId": 3,
      "photo": "https://airbnbnew.cybersoft.edu.vn/images/phong9.png"
    },
    {
      "id": 10,
      "name": "Hanoi Old Quarter Homestay - Unique Railway View",
      "guestCount": 2,
      "bedRoomCount": 1,
      "bedCount": 1,
      "bathRoomCount": 1,
      "description": "Welcome to our house - a newly renovated apartment & just a step to Old Quarter, Dong Xuan Market, Hoan Kiem Lake...\r\n\r\nYou will get a chance to truly live a Hanoian life with local neighbor, local food & an one-of-a-kind experience of living right beside an unique Hanoi old French style Railway.",
      "price": 23,
      "hasWashingMachine": true,
      "hasIronBoard": true,
      "hasTV": true,
      "hasAirConditioner": true,
      "hasWifi": true,
      "hasKitchen": true,
      "hasParking": true,
      "hasSwimmingPool": false,
      "hasIron": true,
      "locationId": 4,
      "photo": "https://airbnbnew.cybersoft.edu.vn/images/phong10.png"
    },
  ]);
}
export const down = async (queryInterface: QueryInterface) => {
  await queryInterface.bulkDelete('rooms', {}, {});
}

